apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-test
  labels:
    app: claude-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claude-test
  template:
    metadata:
      labels:
        app: claude-test
    spec:
      containers:
      - name: claude-test
        image: your-registry/claude-test:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5