apiVersion: v1
kind: Service
metadata:
  name: claude-test-service
  labels:
    app: claude-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: claude-test